services:
  - type: web
    name: poker-trivia-api
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn poker_api.main:app --host 0.0.0.0 --port 8000"
    autoDeploy: true
