services:
  - type: web
    name: poker-trivia-backend
    env: python
    plan: starter
    buildCommand: pip install -r backend/requirements.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9

services:
  - type: web
    name: poker-trivia-frontend
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: serve -s dist
    rootDir: frontend
